# -*- coding: utf-8 -*-
"""Financial_Sentiment_Market_Mind.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g70ufdNmNK2Q9xJ9NCAL886HoXWJJjdk
"""

import pandas as pd
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

try:
    nltk.data.find('corpora/stopwords')
except LookupError:
    nltk.download('stopwords')

try:
    nltk.data.find('corpora/wordnet')
except LookupError:
    nltk.download('wordnet')


df = pd.read_csv("data.csv")
df.head()

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z]', ' ', text)  # remove numbers & punctuation
    words = text.split()

    words = [lemmatizer.lemmatize(word) for word in words if word not in stop_words]

    return " ".join(words)

df['clean_text'] = df['Sentence'].apply(clean_text)
df.head()

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=5000)

X = tfidf.fit_transform(df['clean_text']).toarray()
y = df['Sentiment']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)

from sklearn.metrics import classification_report, accuracy_score

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

def predict_sentiment(text):
    text_clean = clean_text(text)
    vector = tfidf.transform([text_clean]).toarray()
    prediction = model.predict(vector)
    return prediction[0]

print(predict_sentiment("Company reports strong quarterly earnings"))
print(predict_sentiment("Company faces major lawsuit and losses"))

import spacy
try:
    nlp = spacy.load("en_core_web_sm")
except:
    import os
    os.system("python -m spacy download en_core_web_sm")
    nlp = spacy.load("en_core_web_sm")

def extract_companies(text):
    doc = nlp(text)
    companies = []

    for ent in doc.ents:
        if ent.label_ == "ORG":  # Organization
            companies.append(ent.text)

    return companies

text = "Tesla and Apple stocks surged after strong earnings"
print(extract_companies(text))

company_to_ticker = {
    "Tesla": "TSLA",
    "Apple": "AAPL",
    "Microsoft": "MSFT",
    "Amazon": "AMZN",
    "Google": "GOOGL",
    "Nvidia": "NVDA"
}

def analyze_news(text):
    companies = extract_companies(text)
    sentiment = predict_sentiment(text)

    results = []

    for company in companies:
        ticker = company_to_ticker.get(company, "UNKNOWN")

        results.append({
            "company": company,
            "ticker": ticker,
            "sentiment": sentiment
        })

    return results

news = "Tesla stock jumps while Apple faces declining sales"

print(analyze_news(news))

[
  {"company": "Tesla", "ticker": "TSLA", "sentiment": "positive"},
  {"company": "Apple", "ticker": "AAPL", "sentiment": "negative"}
]


import feedparser

url = "https://finance.yahoo.com/rss/topstories"
feed = feedparser.parse(url)

for entry in feed.entries[:5]:
    print(entry.title)

results = []

for entry in feed.entries[:10]:
    headline = entry.title
    analysis = analyze_news(headline)

    for item in analysis:
        item["headline"] = headline
        results.append(item)

results

import pandas as pd

results_df = pd.DataFrame(results)
results_df

summary = results_df.groupby("ticker")["sentiment"].value_counts().unstack().fillna(0)
summary


import streamlit as st

st.title("📈 Market-Mind Dashboard")

st.subheader("Live Sentiment Analysis")

st.dataframe(results_df)

st.subheader("Sentiment Summary")
st.dataframe(summary)

import time

st.set_page_config(page_title="Market-Mind", layout="wide")

st.title("📈 Market-Mind: Financial Sentiment Dashboard")

data = {
    "ticker": ["TSLA", "AAPL", "MSFT", "TSLA", "AAPL"],
    "sentiment": ["positive", "negative", "positive", "positive", "neutral"]
}
df = pd.DataFrame(data)

summary = df.groupby("ticker")["sentiment"].value_counts().unstack().fillna(0)

col1, col2, col3 = st.columns(3)

col1.metric("📊 Total News", len(df))
col2.metric("🟢 Positive", (df['sentiment'] == "positive").sum())
col3.metric("🔴 Negative", (df['sentiment'] == "negative").sum())

st.divider()

col1, col2 = st.columns(2)

with col1:
    st.subheader("Sentiment by Stock")
    st.bar_chart(summary)

with col2:
    st.subheader("Sentiment Distribution")
    st.bar_chart(df['sentiment'].value_counts())

st.divider()

st.subheader("📄 Latest Headlines Data")
st.dataframe(df, use_container_width=True)


from streamlit_autorefresh import st_autorefresh

st_autorefresh(interval=30000, key="datarefresh")

import matplotlib.pyplot as plt

fig, ax = plt.subplots()
summary.plot(kind="bar", ax=ax)
st.pyplot(fig)

st.sidebar.header("Filters")

selected_ticker = st.sidebar.selectbox(
    "Select Stock",
    options=df['ticker'].unique()
)

filtered_df = df[df['ticker'] == selected_ticker]

st.subheader(f"Data for {selected_ticker}")
st.dataframe(filtered_df)

